    version: 2
jobs:
  test:
    docker:
      - image: hashicorp/terraform
    working_directory: ~/porch-guru
    steps:
      - checkout
      - run:
          name: Initialize Terraform
          command: terraform init